version: '3.2'

services:

  vault:
    image: vault:1.4.3
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: YOUR_TOKEN_HERE
    cap_add:
      - IPC_LOCK
    expose:
      - 8200
    networks:
      - internal

  supersecret:
    build: ./
    image: algolia/supersecretmessage:latest
    container_name: supersecret
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: YOUR_TOKEN_HERE
      #VIRTUAL_HOST: "secretmessage.example.org"
      #VIRTUAL_PROTO: "http"
      #VIRTUAL_PORT: 1234
    ports:
      - "1234"
    depends_on:
      - vault
    labels:
      - traefik.enable=true
      - traefik.http.routers.secretmessage.entrypoints=websecure
      - traefik.http.routers.secretmessage.tls=true
      - traefik.http.routers.secretmessage.tls.certresolver=le
      - traefik.http.routers.secretmessage.rule=Host(`secretmessage.example.org`)
      - traefik.http.services.secretmessage.loadbalancer.server.port=1234
    networks:
      - internal
      - traefik_proxy

networks:
  internal:
  traefik_proxy:
    external: true
